# Generated by Django 4.2.5 on 2023-09-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reported_by', models.CharField(max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
