# Generated by Django 4.2.5 on 2023-09-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreport',
            options={'verbose_name_plural': 'Reportes de Bugs'},
        ),
        migrations.AddField(
            model_name='bugreport',
            name='area',
            field=models.CharField(default='ValorPredeterminado', max_length=100, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='causal',
            field=models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('Documentacion', 'Documentacion'), ('Testing', 'Testing'), ('Diseño', 'Diseño')], default='Desarrollo', max_length=50),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='project_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre del Proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bugreport',
            name='severity',
            field=models.CharField(choices=[('Bloqueante', 'Bloqueante'), ('Funcional', 'Funcional'), ('Presentacion', 'Presentacion')], default=1, max_length=20, verbose_name='Severidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], default=1, max_length=20, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='reported_by',
            field=models.CharField(max_length=100, verbose_name='Reportado por'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nombre del Bug'),
        ),
    ]
