# Generated by Django 4.2.5 on 2023-09-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_bugreport_options_bugreport_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='description',
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='area',
            field=models.CharField(max_length=100, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='causal',
            field=models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('Documentacion', 'Documentacion'), ('Testing', 'Testing'), ('Diseño', 'Diseño')], max_length=50),
        ),
    ]
