# Generated by Django 4.2.5 on 2023-09-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_remove_bugreport_description_alter_bugreport_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='date_reported',
            field=models.DateField(verbose_name='Fecha de Creación'),
        ),
    ]
