# Generated by Django 4.2.5 on 2023-09-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_bugreport_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='area',
            field=models.CharField(choices=[('AXCES', 'AXCES'), ('Gestion Del Riesgo', 'Gestion Del Riesgo'), ('Mercadeo', 'Mercadeo'), ('Transcersal', 'Transcersal')], max_length=100, verbose_name='Área'),
        ),
    ]
