# Generated by Django 4.2.5 on 2023-09-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_bugreport_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='causal',
            field=models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('Documentacion', 'Documentacion'), ('Testing', 'Testing'), ('Diseño', 'Diseño'), ('Analisis', 'Analisis')], max_length=50),
        ),
    ]
