# Generated by Django 4.2.5 on 2023-09-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_alter_bugreport_causal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='area',
            field=models.CharField(choices=[('AXCES', 'AXCES'), ('Gestion Del Riesgo', 'Gestion Del Riesgo'), ('Mercadeo', 'Mercadeo'), ('Transversal', 'Transversal')], max_length=100, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='assigned_to',
            field=models.CharField(max_length=100, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='link',
            field=models.URLField(verbose_name='Enlace'),
        ),
    ]
